### PR TITLE
Update util.typ

### LINKED ISSUE #13: Regression in 0.1.3 with figure caption
This code
```typst
#import "@preview/lemmify:0.1.3" : *
#let (theorem, rules) = default-theorems("thm-group")
#show: rules
#theorem[Theorem content goes here.]
```
gives the error
```
error: cannot access fields on type none
   ┌─ @preview/lemmify:0.1.3/src/util.typ:25:16
   │
25 │     fig.caption.body,
   │                 ^^^^

help: error occurred while applying show rule to this figure
   ┌─ @preview/lemmify:0.1.3/src/util.typ:7:4
   │  
 7 │ ╭     figure(
 8 │ │       content,
 9 │ │       caption: name,
10 │ │       kind: group,
11 │ │       supplement: subgroup,
12 │ │       numbering: numbering
13 │ │     )
   │ ╰─────^
```
Which is probably wrong unless I'm missing something. Perhaps if should be `if figure.has("caption") { figure.caption.body }`?

(This reached me via web app feedback.)

### PR DESCRIPTION
**Pull request by ParadaCarleton**
I _think_ this fixes #13. But because Typst is too new to have stuff like testing frameworks, it's a bit hard to know :sweat_smile:

It should be possible to set up a very basic GitHub workflow to test whether anything fails to compile, though. (@laurmaedje would you happen to have code on hand for this?)

### CODE REVIEW

**Comment by Marmare314** [comment]
There are already some examples in which this probably also fails. I just didn't check them since I was in a hurry. But adding some CI would be awesome and should be "relatively" simple now that png export is supported.

This unfortunately reintroduces #9. I think that `if figure.has("caption") { figure.caption.body }` is the right thing to here as suggested in #13.
If you want to update this PR, I'm happy to merge it later (after checking the sample files this time 😅).

**Comment by ParadaCarleton** [comment]
When I tried that approach, I got:
```typst
error: function `figure` does not contain field `has`
   ┌─ lemmify/src/util.typ:24:19
   │
24 │   body = if figure.has("caption") { 
   │                    ^^^

help: error occurred while applying show rule to this figure
   ┌─ lemmify/src/util.typ:7:4
   │  
 7 │ ╭     figure(
 8 │ │       content,
 9 │ │       caption: name,
10 │ │       kind: group,
11 │ │       supplement: subgroup,
12 │ │       numbering: numbering
13 │ │     )
   │ ╰─────^
```

**Comment by laurmaedje** [comment]
It should have been `if fig.has("caption") { fig.caption.body }`.

**Comment by ParadaCarleton** [comment]
> It should have been `if fig.has("caption") { fig.caption.body }`.

Thanks!

**Comment by ParadaCarleton** [comment]
I accidentally opened two PRs so I'm gonna close this now :sweat_smile:

**Pull request closed without merging**
